### ISSUE TITLE
lines not visible

### ISSUE THREAD

**Issue by smolleyes** [alexcheng1982/google-maps-ruler#1]
hi 

first thanks for this module ;)

when i load my page the first time will all the scripts and init the ruler everything works fine, now i change page then return to the page where i draw my map (so i create a new map and reload the ruler too) i can add points, move them etc but polylines are not visibles :/ , an idear on why ?

no way to force redraw of the lines ? or how can i destroy the ruler objetc then reinit like if i was reloading the whole page ? 

ps: possible to add a function to remove all lines and points at once ? 

thanks

**Comment by alexcheng1982** [comment]
I added two new APIs in v1.0.2.
- `clear` to clear all points
- `unbind` to remove the binding to Google Map

So you can use `gmruler.clear()` to clear all points. `gmruler.unbind()` can be used to remove the binding to Google Map object, then you can call `init()` to bind to the map object again.

**Comment by smolleyes** [comment]
hi

thanks for the update

clear works well :)

but same problem for me even with the unbind()

here is the function i use to load my map

```
function initGoogleMap(adresses) {
  var head = document.getElementsByTagName('head')[0];
  // Save the original method
  var insertBefore = head.insertBefore;
  // Replace it!
  head.insertBefore = function (newElement, referenceElement) {
    if (newElement.href && newElement.href.indexOf('https://fonts.googleapis.com/css?family=Roboto') === 0) {
      console.info('Prevented Roboto from loading!');
      return;
    }
    insertBefore.call(head, newElement, referenceElement);
  };

  var latlng = new google.maps.LatLng(48.688974, 2.510836);
  counter = 0;
  var mapOptions = {
    zoom: 8,
    center: latlng,
    mapTypeId: 'roadmap'
  }
  map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);

  var myStyles =[
      {
        "featureType": "poi",
        "elementType": "all",
        "stylers": [
          { "visibility": "off" }
        ]
      },{
        "featureType": "transit",
        "stylers": [
          { "visibility": "off" }
        ]
      }
    ]
  map.setOptions({styles: myStyles});

  //map ruler init
  gmruler.unbind();
  gmruler.init(map, {
    distanceUnit: 'km',
    strokeWeight : 5,
    strokeColor: "red"
  })
  // add markers
  addMarkers(adresses)
}

```

everything works i just don t see the red lines...

an idear ?

thanks

**Comment by alexcheng1982** [comment]
I think I found out the root cause of this issue. It's because that the line object was not bound to the map object after the map was recreated. 

Please note, in 1.0.3 I renamed `init` method to `bind` to match the naming of `unbind` method. So you need to update your code to use `bind` method instead.

It's **recommended** but _not required_ to call `unbind` before calling `bind`. `bind` will initialise correctly, but `unbind` is recommended to release resources and remove event listener on the map object.

**Comment by smolleyes** [comment]
hi

everything works well now :) thanks for the fix ! 

i close the issue 

thanks again :+1:
